// Scans gallery/<year>/ folders, writes gallery-manifest.js with the photo list.
// Runs locally and on Vercel (via "build" script in package.json).
import { readdir, writeFile } from 'node:fs/promises';
import { join } from 'node:path';

const ROOT = 'gallery';
const OUT = 'gallery-manifest.js';
const VALID = /\.(jpe?g|png|webp|avif|gif)$/i;

const yearDirs = (await readdir(ROOT, { withFileTypes: true }))
  .filter(d => d.isDirectory() && /^\d{4}$/.test(d.name))
  .map(d => d.name)
  .sort()
  .reverse();

const manifest = {};
let total = 0;
for (const year of yearDirs) {
  const files = (await readdir(join(ROOT, year)))
    .filter(f => VALID.test(f))
    .sort();
  manifest[year] = files.map(f => ({ file: f, caption: deriveCaption(f, year) }));
  total += files.length;
}

function deriveCaption(filename, year) {
  const base = filename.replace(/\.[^.]+$/, '');
  // Facebook export style — long random digits, drop and use the year tag
  if (/^\d{8,}/.test(base)) return `BEER OLYMPICS · ${year}`;
  // IMG-YYYYMMDD-WAxxxx → just date the year
  if (/^IMG-\d{8}-WA/.test(base)) return `MATCH DAY · ${year}`;
  // YYYYMMDD_HHMMSS phone format
  if (/^\d{8}_\d{6}/.test(base)) return `MATCH DAY · ${year}`;
  // human-readable filename — clean up
  return base.replace(/[_-]+/g, ' ').toUpperCase().slice(0, 48);
}

const body = `// AUTO-GENERATED by build-gallery.mjs — do not edit by hand.
window.GALLERY = ${JSON.stringify(manifest, null, 2)};
`;

await writeFile(OUT, body);
console.log(`✓ wrote ${OUT} — ${total} photos across ${yearDirs.length} year(s)`);
for (const y of yearDirs) console.log(`    ${y}: ${manifest[y].length}`);
