// Scans gallery/<year>/ folders, writes gallery-manifest.js with the photo list.
// Runs locally and on Vercel (via "build" script in package.json).
import { readdir, writeFile } from 'node:fs/promises';
import { join } from 'node:path';

const ROOT = 'gallery';
const OUT = 'gallery-manifest.js';
const VALID = /\.(jpe?g|png|webp|avif|gif)$/i;

// Hand-written captions for photos whose filenames tell us nothing.
// Key is "<year>/<filename>"; anything not listed falls back to deriveCaption().
const CAPTIONS = {
  '2023/nick-chris-hero.jpg': 'JOINT CHAMPIONS · TIE UNBROKEN',
  '2023/533251130_800782689011988_288374663152854540_n.jpg': 'DARTS · 2023',
  '2023/drift-trikes-podium.jpg': 'DRIFT TRIKES PODIUM',
  '2024/IMG-20240921-WA0006.jpeg': 'PUB GOLF · THE COURSE',
  '2024/IMG-20240921-WA0007.jpeg': 'PUB GOLF · RULES & PENALTIES',
  '2024/IMG-20240921-WA0010.jpeg': 'MID RANGE · PRO SERIES',
  '2024/20240921_145110.jpg': 'TASTING FLIGHT · 2024',
  '2024/679991313_799936166530288_8013210291246706217_n.jpg': 'SOMBRERO SESSION · 2024',
  '2024/683470080_1290906005799599_2862683464075386034_n.jpg': 'TASTING FLIGHT · 2024',
  '2024/684202887_995327029844712_2782361927940386372_n.jpg': "PUB GOLF · NICK'S CARD",
  '2024/685902866_938666442380854_607208713218830561_n.jpg': 'TOPGOLF · UNDER LIGHTS',
  '2024/686920876_1306078737537335_5191454605545000473_n.jpg': 'OFFICIAL TEAM KIT',
  '2025/champ-2025-portrait.jpg': 'THE CHAMP · CATCH HIM IF YOU CAN',
};

const yearDirs = (await readdir(ROOT, { withFileTypes: true }))
  .filter(d => d.isDirectory() && /^\d{4}$/.test(d.name))
  .map(d => d.name)
  .sort()
  .reverse();

const manifest = {};
let total = 0;
for (const year of yearDirs) {
  const files = (await readdir(join(ROOT, year)))
    .filter(f => VALID.test(f))
    .sort();
  manifest[year] = files.map(f => ({
    file: f,
    caption: CAPTIONS[`${year}/${f}`] || deriveCaption(f, year),
  }));
  total += files.length;
}

function deriveCaption(filename, year) {
  const base = filename.replace(/\.[^.]+$/, '');
  // Facebook export style — long random digits, drop and use the year tag
  if (/^\d{8,}/.test(base)) return `BEER OLYMPICS · ${year}`;
  // IMG-YYYYMMDD-WAxxxx → just date the year
  if (/^IMG-\d{8}-WA/.test(base)) return `MATCH DAY · ${year}`;
  // YYYYMMDD_HHMMSS phone format
  if (/^\d{8}_\d{6}/.test(base)) return `MATCH DAY · ${year}`;
  // human-readable filename — clean up
  return base.replace(/[_-]+/g, ' ').toUpperCase().slice(0, 48);
}

const body = `// AUTO-GENERATED by build-gallery.mjs — do not edit by hand.
window.GALLERY = ${JSON.stringify(manifest, null, 2)};
`;

await writeFile(OUT, body);
console.log(`✓ wrote ${OUT} — ${total} photos across ${yearDirs.length} year(s)`);
for (const y of yearDirs) console.log(`    ${y}: ${manifest[y].length}`);
